# Generated by Django 4.2.2 on 2023-07-19 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('search_link', models.URLField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('car_image', models.TextField(default=0, null=True)),
                ('car_link', models.TextField(default=0, null=True)),
                ('car_name', models.TextField(default=0, null=True)),
                ('car_price', models.TextField(default=0, null=True)),
                ('car_specific_params', models.TextField(default=0, null=True)),
                ('car_description', models.TextField(default=0, null=True)),
                ('car_pushed', models.TextField(default=0, null=True)),
                ('car_geo', models.TextField(default=0, null=True)),
                ('car_date', models.TextField(default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
